# Generated by Django 5.0.4 on 2024-04-15 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HouseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeofhouse', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('add', models.IntegerField()),
            ],
        ),
    ]
