# Generated by Django 5.0.4 on 2024-04-15 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housetype',
            name='add',
            field=models.IntegerField(blank=True),
        ),
    ]
