# Generated by Django 5.0.4 on 2024-04-19 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_rename_typeofhouse_housetype_typesofhouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_product', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('add', models.IntegerField(blank=True)),
            ],
        ),
        migrations.RenameField(
            model_name='housetype',
            old_name='typesofhouse',
            new_name='type_of_house',
        ),
    ]
