# Generated by Django 5.0.4 on 2024-04-19 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0004_products_rename_typesofhouse_housetype_type_of_house'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('material_type', models.CharField(choices=[('floor', 'Floor'), ('paint', 'Paint')], max_length=50)),
                ('price_per_square_meter', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
