# Generated by Django 5.0.4 on 2024-04-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0005_material_delete_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloorMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_material', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('price_per_square_meter', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Material',
        ),
    ]
