# Generated by Django 5.0.4 on 2024-04-26 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0007_wallmaterial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BathroomMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bathroom_material', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('price_per_square_meter', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
