# Generated by Django 5.0.4 on 2024-04-26 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0008_bathroommaterial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bathroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='BathroomItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='BathroomMaterial',
        ),
        migrations.AddField(
            model_name='bathroom',
            name='bathroom_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.bathroomitem'),
        ),
        migrations.AddField(
            model_name='bathroom',
            name='bathroom_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.materialtype'),
        ),
    ]
