# Generated by Django 5.0.4 on 2024-04-26 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0009_bathroom_bathroomitem_materialtype_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bathroomitem',
            old_name='items_name',
            new_name='bathroom_item',
        ),
        migrations.AddField(
            model_name='bathroomitem',
            name='bathroom_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calculator.materialtype'),
        ),
        migrations.AddField(
            model_name='bathroomitem',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='Bathroom',
        ),
    ]
