# Generated by Django 5.0.4 on 2024-04-26 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0011_alter_bathroomitem_bathroom_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='bathroomitem',
            name='add',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
