# Generated by Django 5.0.4 on 2024-05-06 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0013_materialtype_price_per_square_meter'),
    ]

    operations = [
        migrations.CreateModel(
            name='BathroomShower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_shower', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('add', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bathroomsink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_sink', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('add', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='BathroomSpecialItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_item', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('add', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='BathroomToilet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_toilet', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('add', models.IntegerField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='BathroomItem',
        ),
        migrations.DeleteModel(
            name='MaterialType',
        ),
    ]
